/- Check.lean — axiom audit.  Every theorem in the package must depend on at most
   propext, Quot.sound, Classical.choice.  Regenerate the list if theorems are added. -/
import Rule737
import Markets
import Balance
import Rulebook
import Orders
import Strategic
import SetterRace
import Closure
import Conformance
import Collisions
import TapeConformance
import Algebra
import MoreRules
import PathIndependence
import WheelInformation
import ClauseComplete
open Rule737

#print axioms Rule737.sum_append
#print axioms Rule737.seq_conserves
#print axioms Rule737.seq_assoc
#print axioms Rule737.seq_id_left
#print axioms Rule737.seq_id_right
#print axioms Rule737.setterOp_conserves
#print axioms Rule737.wheelOp_conserves
#print axioms Rule737.wheelOpFull_conserves
#print axioms Rule737.ptOp_conserves
#print axioms Rule737.rule737Op_conserves
#print axioms Rule737.rule737Op_eq
#print axioms Rule737.ladderOp_conserves
#print axioms Rule737.waterFill_map
#print axioms Rule737.priceTime_not_anonymous
#print axioms Rule737.priceTime_mono
#print axioms Rule737.waterFill_mono
#print axioms Rule737.serial_band_incompatible
#print axioms Rule737.ex_incompatible
#print axioms Rule737.ptLadder_sum_le
#print axioms Rule737.ladder_unique
#print axioms Rule737.ex_wheelS_agrees
#print axioms Rule737.Band_Balanced
#print axioms Rule737.passS_sum
#print axioms Rule737.passS_leftover_le
#print axioms Rule737.passS_band
#print axioms Rule737.passS_eq
#print axioms Rule737.wheelS_zero
#print axioms Rule737.wheelS_band
#print axioms Rule737.wheelS_band_explicit
#print axioms Rule737.wheelS_balanced
#print axioms Rule737.wheelS_unit_balanced
#print axioms Rule737.wheelS_within_L
#print axioms Rule737.wheelS_within_L_explicit
#print axioms Rule737.crossKey_lex
#print axioms Rule737.foldl_sel_mem
#print axioms Rule737.crossPrice2_lex
#print axioms Rule737.ex_cross2
#print axioms Rule737.netCost_le_cap
#print axioms Rule737.fee_adjusted_spread
#print axioms Rule737.validExemptionAttestation_iff
#print axioms Rule737.bool_true_or_false
#print axioms Rule737.roundLotSize600_new_stock
#print axioms Rule737.roundLotSize600_low
#print axioms Rule737.roundLotSize600_middle40
#print axioms Rule737.roundLotSize600_middle10
#print axioms Rule737.roundLotSize600_high
#print axioms Rule737.checkedRoundLotSize600_new_stock
#print axioms Rule737.checkedRoundLotSize600_on_grid
#print axioms Rule737.checkedRoundLotSize600_off_grid
#print axioms Rule737.checkedRoundLotSize600_boundaries
#print axioms Rule737.minimumIncrementIndicator_amended_not_september2026
#print axioms Rule737.accessFeeCap610_legacy_at_or_above_dollar
#print axioms Rule737.feeCap_eq_accessFeeCap610_legacy_dollar
#print axioms Rule737.accessFeeCap610_legacy_below_dollar
#print axioms Rule737.accessFeeCap610_amended_at_or_above_dollar
#print axioms Rule737.accessFeeCap610_amended_below_dollar
#print axioms Rule737.rule610_exemption
#print axioms Rule737.rule610_amended_profile_not_september2026
#print axioms Rule737.rule611_no_trade_through_allowed
#print axioms Rule737.rule611_all_exceptions_decidable
#print axioms Rule737.operativePeriodFor612_january_through_march
#print axioms Rule737.operativePeriodFor612_july_through_september
#print axioms Rule737.rule612_amended_profile_not_september2026
#print axioms Rule737.minimumTick612_legacy_subdollar
#print axioms Rule737.minimumTick612_legacy_at_or_above_dollar
#print axioms Rule737.rule612_iff_minimumTick612_legacy
#print axioms Rule737.minimumTick612_amended_subdollar
#print axioms Rule737.minimumTick612_amended_new_stock
#print axioms Rule737.minimumTick612_amended_narrow
#print axioms Rule737.minimumTick612_amended_wide
#print axioms Rule737.tenPercentDecline201_iff
#print axioms Rule737.rule201_long_sale_allowed
#print axioms Rule737.all_short_exempt_reasons_decidable
#print axioms Rule737.publicationRoute605_with_plan
#print axioms Rule737.publicationRoute605_without_plan
#print axioms Rule737.requiredImmediateFields605_september
#print axioms Rule737.requiredImmediateFields605_november
#print axioms Rule737.rule605_full_profile_not_september2026
#print axioms Rule737.orderTypes605_complete
#print axioms Rule737.coreFields605_complete
#print axioms Rule737.immediateFields605_complete
#print axioms Rule737.nonmarketableFields605_complete
#print axioms Rule737.summaryFields605_complete
#print axioms Rule737.luld_exemption
#print axioms Rule737.nasdaqOrderTypes4702_complete
#print axioms Rule737.nasdaqAttributes4703_complete
#print axioms Rule737.clause_corpus_has_58_entries
#print axioms Rule737.clause_corpus_traceability_complete
#print axioms Rule737.clause_corpus_citations_unique
#print axioms Rule737.clause_corpus_family_counts
#print axioms Rule737.passS_spec
#print axioms Rule737.zip_add_zero
#print axioms Rule737.zip_add_assoc
#print axioms Rule737.wheelS_spec
#print axioms Rule737.wheelS_eq_wheel
#print axioms Rule737.wheel_balanced
#print axioms Rule737.passS_pair
#print axioms Rule737.wheelS_pair
#print axioms Rule737.initS_pair
#print axioms Rule737.pairs_recover
#print axioms Rule737.wheelS_state_eq
#print axioms Rule737.zipWith_pair_mem
#print axioms Rule737.wheel_within_L
#print axioms Rule737.sumU_closed
#print axioms Rule737.uniform_payoff
#print axioms Rule737.uniform_eps
#print axioms Rule737.sumSelf_closed
#print axioms Rule737.uniform_selfpayoff_zero
#print axioms Rule737.uniform_eps_relative
#print axioms Rule737.priceTime_zero
#print axioms Rule737.priceTime_tail_invisible
#print axioms Rule737.priceTime_boundary_invisible
#print axioms Rule737.Pw_le_sum
#print axioms Rule737.rule737full_sum
#print axioms Rule737.t3_only_after_t2
#print axioms Rule737.hidden_depth_lower_bound
#print axioms Rule737.parity_count_fingerprint
#print axioms Rule737.dmm_share_antitone
#print axioms Rule737.filter_sum_mono
#print axioms Rule737.demandAt_antitone
#print axioms Rule737.supplyAt_mono
#print axioms Rule737.foldl_argmax_mono
#print axioms Rule737.foldl_argmax_ge
#print axioms Rule737.crossPrice_maximizes
#print axioms Rule737.ex_cross
#print axioms Rule737.effective_tick
#print axioms Rule737.relative_tick_antitone
#print axioms Rule737.route_to_nbo_no_trade_through
#print axioms Rule737.compliant_of_le
#print axioms Rule737.sip_ge_venue
#print axioms Rule737.sip_order_preserved
#print axioms Rule737.sip_order_inversion_exists
#print axioms Rule737.sip_inversion_bound
#print axioms Rule737.foldl_min_le_init
#print axioms Rule737.foldl_min_le_mem
#print axioms Rule737.bestVenue_le
#print axioms Rule737.fm_some
#print axioms Rule737.fm_none
#print axioms Rule737.fm_mem
#print axioms Rule737.fm_ub
#print axioms Rule737.supplyAt_zero_of_none
#print axioms Rule737.supplyAt_eq_of_ub
#print axioms Rule737.matched_dominated_by_ask_price
#print axioms Rule737.crossPrice_global
#print axioms Rule737.passS_tot_le
#print axioms Rule737.passS_tot_lt
#print axioms Rule737.wheelS_zero_tot
#print axioms Rule737.wheelS_complete
#print axioms Rule737.wheelS_exhausts
#print axioms Rule737.initS_snd
#print axioms Rule737.initS_tot
#print axioms Rule737.initS_fst_sum
#print axioms Rule737.passS_inv
#print axioms Rule737.wheelS_inv
#print axioms Rule737.wheel_exhausts
#print axioms Rule737.discreteCEA_feasible
#print axioms Rule737.discreteCEA_reset_not_composable
#print axioms Rule737.zeroedNYSE
#print axioms Rule737.matchNYSE_conserve
#print axioms Rule737.nyse_price_priority
#print axioms Rule737.lower_le_ref
#print axioms Rule737.ref_le_upper
#print axioms Rule737.bands_widen
#print axioms Rule737.limitState_boundary
#print axioms Rule737.ref_in_bands
#print axioms Rule737.no_short_at_or_below_nbb
#print axioms Rule737.short_ok_when_no_breaker
#print axioms Rule737.eff_at_nbo
#print axioms Rule737.eff_le_quoted
#print axioms Rule737.effSpread2_neg_iff
#print axioms Rule737.pi_le_spread
#print axioms Rule737.midpoint_zero_eff
#print axioms Rule737.loc_mono
#print axioms Rule737.loc_anti
#print axioms Rule737.postOnly_rests_iff
#print axioms Rule737.postOnly_never_takes
#print axioms Rule737.ex_nyse
#print axioms Rule737.ex_luld
#print axioms Rule737.midpoint_inside
#print axioms Rule737.midpoint2_strict_inside
#print axioms Rule737.mpl_no_trade_through
#print axioms Rule737.fillReserve_conserve
#print axioms Rule737.fillReserve_replenish
#print axioms Rule737.reserve_certificate
#print axioms Rule737.dOrder_within
#print axioms Rule737.dOrder_compliant
#print axioms Rule737.primaryPeg_le_limit
#print axioms Rule737.marketPeg_le_limit
#print axioms Rule737.marketPeg_no_lock
#print axioms Rule737.primaryPeg_mono
#print axioms Rule737.foldl_min_opt_sub
#print axioms Rule737.selfhelp_raises_nbo
#print axioms Rule737.dist_comm
#print axioms Rule737.dist_self
#print axioms Rule737.lex2
#print axioms Rule737.crossPrice3_lex
#print axioms Rule737.dmm_clears
#print axioms Rule737.dmm_conserve
#print axioms Rule737.ex_auction
#print axioms Rule737.pt_zero
#print axioms Rule737.pt_length
#print axioms Rule737.zip_sub_zero
#print axioms Rule737.zip_zero_add
#print axioms Rule737.priceTime_comp
#print axioms Rule737.conformsPT_comp
#print axioms Rule737.waterFill_level_comp
#print axioms Rule737.waterFill_two_equal_no_single_share
#print axioms Rule737.wheel_not_path_independent
#print axioms Rule737.splitLive_append
#print axioms Rule737.splitLive_live
#print axioms Rule737.totW_append
#print axioms Rule737.length_append_eq
#print axioms Rule737.mem_findLive_iff
#print axioms Rule737.findLive_tot
#print axioms Rule737.findLive_head
#print axioms Rule737.findLive_of_live
#print axioms Rule737.liveAllocs_append
#print axioms Rule737.splitLive_fst_dead
#print axioms Rule737.liveAllocs_of_dead
#print axioms Rule737.liveAllocs_findLive
#print axioms Rule737.TwoPhase.allLow
#print axioms Rule737.TwoPhase.appendHigh
#print axioms Rule737.TwoPhase.consCases
#print axioms Rule737.TwoPhase.mem
#print axioms Rule737.mem_liveAllocs
#print axioms Rule737.AllAtP_band
#print axioms Rule737.pointer_wheel_instance
#print axioms Rule737.pointer_wheel_odd_instance
#print axioms Rule737.parity_pointer_not_identified_from_prints
#print axioms Rule737.no_parity_conformance_from_queue_and_prints
#print axioms Rule737.future_sufficient_summary_requires_pointer_information
#print axioms Rule737.succ_mod_ne_self
#print axioms Rule737.saturated_future_equiv_iff
#print axioms Rule737.saturated_future_sufficient_injective
#print axioms Rule737.runW_x0
#print axioms Rule737.runW_stable
#print axioms Rule737.stepW_adv
#print axioms Rule737.stepW_partial
#print axioms Rule737.stepW_allAtP
#print axioms Rule737.runW_allAtP
#print axioms Rule737.liveAllocs_initW_zero
#print axioms Rule737.initW_allAtP
#print axioms Rule737.initW_atWheelPhase
#print axioms Rule737.runW_atWheelPhase
#print axioms Rule737.runW_band
#print axioms Rule737.runW_balanced
#print axioms Rule737.runW_unit_balanced
#print axioms Rule737.stepW_le
#print axioms Rule737.stepW_tot_conserve
#print axioms Rule737.stepW_tot_lt
#print axioms Rule737.stepW_lot_pos
#print axioms Rule737.runW_lot_pos
#print axioms Rule737.runW_stops_of_tot_lt_fuel
#print axioms Rule737.runW_tot_conserve
#print axioms Rule737.runWFull_stopped
#print axioms Rule737.runWFull_allocates_first
#print axioms Rule737.stepW_split
#print axioms Rule737.stepW_zero
#print axioms Rule737.runW_comp
#print axioms Rule737.runWFull_comp
#print axioms Rule737.runWFull_comp_reachable
#print axioms Rule737.map_zero_sum
#print axioms Rule737.Pw_map_zero
#print axioms Rule737.give_le_L
#print axioms Rule737.give_le_r
#print axioms Rule737.give_le_x
#print axioms Rule737.give_of_pos
#print axioms Rule737.wheelRound_le_L
#print axioms Rule737.wheelRound_cap
#print axioms Rule737.wheelRound_sum
#print axioms Rule737.wheelRound_sum_le
#print axioms Rule737.wheelRound_full
#print axioms Rule737.wheelRound_length
#print axioms Rule737.wheel_length
#print axioms Rule737.wheel_sum
#print axioms Rule737.Pw_zip_add
#print axioms Rule737.wheel_cap
#print axioms Rule737.rule737_setter_cap
#print axioms Rule737.rule737_sum
#print axioms Rule737.wheelRound_eq_priceTime_of_large_lot
#print axioms Rule737.priceTime_cap
#print axioms Rule737.priceTime_sum_le
#print axioms Rule737.priceTime_serial
#print axioms Rule737.book_share_le_depth_share
#print axioms Rule737.book_share_le_depth_share_mem
#print axioms Rule737.ex_rule737
#print axioms Rule737.ex_waterfill
#print axioms Rule737.ex_within_L
#print axioms Rule737.ex_book_share
#print axioms Rule737.ex_priceTime
#print axioms Rule737.priceTime_feasible
#print axioms Rule737.priceTime_serial'
#print axioms Rule737.serial_unique
#print axioms Rule737.conformsPT_iff
#print axioms Rule737.zeroed_levels_sum
#print axioms Rule737.matchAsks_conserve
#print axioms Rule737.price_priority
#print axioms Rule737.no_fill_above_limit
#print axioms Rule737.foldl_min_opt_mono
#print axioms Rule737.foldl_min_opt_le
#print axioms Rule737.nbo_le_protected
#print axioms Rule737.oddlot_not_protected
#print axioms Rule737.sweep_conserve
#print axioms Rule737.iso_compliance
#print axioms Rule737.slide_no_lock
#print axioms Rule737.slide_le_limit
#print axioms Rule737.ex_book
#print axioms Rule737.ex_nbo
#print axioms Rule737.ex_sweep
#print axioms Rule737.setter_race_no_pure_NE
#print axioms Rule737.race_spend
#print axioms Rule737.sq_nonneg_int
#print axioms Rule737.tullock_best_response
#print axioms Rule737.tullock_symmetric_foc
#print axioms Rule737.tullock_dissipation
#print axioms Rule737.dissipation_increasing
#print axioms Rule737.dmm_option_dilution
#print axioms Rule737.dmm_option_spread
#print axioms Rule737.dmm_advantage
#print axioms Rule737.undercut_wins
#print axioms Rule737.fee_cut_captures
#print axioms Rule737.fee_gap_bounded
#print axioms Rule737.ex_tullock
#print axioms Rule737.ex_tullock_dev
#print axioms Rule737.allocatedList_append
#print axioms Rule737.runWFull_consuming_step
#print axioms Rule737.runWFull_partial_head
#print axioms Rule737.runWFull_advance_head
#print axioms Rule737.runWFull_head_allocation
#print axioms Rule737.nextWFill_head
#print axioms Rule737.nextWFill_crosses_allowance
#print axioms Rule737.validWheelPhase_probe_equiv_implies
#print axioms Rule737.wheelFiberSufficient_pointer_injective
#print axioms Rule737.wheelPointerCode_fiber_sufficient
#print axioms Rule737.phaseState_length
#print axioms Rule737.phaseState_reachable
#print axioms Rule737.phaseState_first_fill
#print axioms Rule737.phaseState_allowance_probe
#print axioms Rule737.phaseState_probe_equiv_iff
#print axioms Rule737.phaseState_future_equiv_iff
#print axioms Rule737.wheelPhaseCode_sufficient
#print axioms Rule737.wheelPhaseSufficient_injective
#print axioms Rule737.phaseState_capacities
#print axioms Rule737.phaseState_claims_large
#print axioms Rule737.phaseState_validWheelPhase
#print axioms Rule737.phaseState_full_allocated_zero
#print axioms Rule737.phaseState_full_observation
#print axioms Rule737.phaseState_full_pointer_sufficient
#print axioms Rule737.phaseState_full_summary_injective
#print axioms Rule737.allowance_from_cumulative
#print axioms Rule737.runW_allowance_phase
#print axioms Rule737.phaseState_labels
#print axioms Rule737.cyclic_label_injective
#print axioms Rule737.phaseState_labels_unique
#print axioms Rule737.splitLive_relabel
#print axioms Rule737.findLive_relabel
#print axioms Rule737.totW_relabel
#print axioms Rule737.stepW_relabel
#print axioms Rule737.runW_relabel
#print axioms Rule737.runWFull_relabel
#print axioms Rule737.wheel_book_share_counterexample
#print axioms Rule737.ex_phase_state_separation
#print axioms Rule737.sum_app
#print axioms Rule737.jump_tape_invisible
#print axioms Rule737.jump_depth_detected
#print axioms Rule737.honest_conforms
#print axioms Rule737.rotations_length
#print axioms Rule737.rotations_self
#print axioms Rule737.length_flatMap_const
#print axioms Rule737.candidates_length
#print axioms Rule737.initW_mem_candidates
#print axioms Rule737.replay_length
#print axioms Rule737.replay_append
#print axioms Rule737.wheelConsistent_sound
#print axioms Rule737.wheelConsistent_complete
#print axioms Rule737.wheelConsistent_honest
#print axioms Rule737.wheelConsistent_prefix
#print axioms Rule737.swaps1_mono
#print axioms Rule737.nbhd_mono
#print axioms Rule737.conformsPTδ_mono
#print axioms Rule737.conformsPTδ_of_conformsPT
#print axioms Rule737.swap_mem_swaps1
#print axioms Rule737.jump_masked
#print axioms Rule737.ex_candidates
#print axioms Rule737.ex_honest
#print axioms Rule737.ex_reset_rejected
#print axioms Rule737.ex_tape_jump
#print axioms Rule737.ex_masked
#print axioms Rule737.ex_not_masked

#print axioms Rule737.twoOrder_masking_iff
#print axioms Rule737.ex_equal_size_clock_jump
