/- Conformance.lean — regression harness on synthetic queue-aligned allocation records. -/
import Rule737
import Rulebook
import Balance
namespace Rule737

/-- Linear congruential generator for reproducible synthetic queues. -/
def lcg (s : Nat) : Nat := (1103515245 * s + 12345) % 2147483648

def synthQueue : Nat → Nat → List Nat
  | 0, _ => []
  | n + 1, s => let s' := lcg s; (100 * (1 + s' % 9)) :: synthQueue n s'

/-- A fill vector, possibly corrupted: swap 100 shares from position i to j. -/
def corrupt (prints : List Nat) (i j : Nat) : List Nat :=
  prints.mapIdx (fun k v => if k = i then v - 100 else if k = j then v + 100 else v)

def trial (seed n x : Nat) : Bool × Bool :=
  let Q := synthQueue n seed
  let good := priceTime Q x
  let bad := corrupt good 0 (n - 1)
  (conformsPT Q good x, conformsPT Q bad x)

/-- Run 200 seeds: every honest record conforms; every corrupted record is rejected. -/
def runTrials (k : Nat) : Nat × Nat :=
  (List.range k).foldl (fun (acc : Nat × Nat) s =>
    let (g, b) := trial (s + 1) 8 2500
    (acc.1 + (if g then 1 else 0), acc.2 + (if b then 0 else 1))) (0, 0)

#eval runTrials 200

/-! ### Mutation harness

`runTrials` only exercises queue-aligned allocation records generated by `priceTime` itself, so its
honest half can never fail.  The harness below applies four independent
mutations to each honest allocation record and counts rejections. Expected:
every honest record accepted, every mutant rejected. -/

/-- Four mutations of a fill vector: move a lot forward, move a lot backward,
    add a lot (over-fill), drop a lot (under-fill). -/
def mutants (prints : List Nat) : List (List Nat) :=
  let n := prints.length
  [ corrupt prints 0 (n - 1),
    corrupt prints (n - 1) 0,
    prints.mapIdx (fun k v => if k = n - 1 then v + 100 else v),
    prints.mapIdx (fun k v => if k = 0 then v - 100 else v) ]

/-- One seed: (honest accepted?, number of mutants rejected out of 4). -/
def mtrial (seed n : Nat) : Bool × Nat :=
  let Q := synthQueue n seed
  let x := 100 * (1 + (lcg (seed + 99)) % 40)
  let good := priceTime Q x
  (conformsPT Q good x,
   (mutants good).foldl (fun acc m => acc + (if conformsPT Q m x then 0 else 1)) 0)

/-- Over `k` seeds with random incoming size: (honest accepted, mutants rejected, mutants total). -/
def runMutation (k : Nat) : Nat × Nat × Nat :=
  (List.range k).foldl (fun (acc : Nat × Nat × Nat) s =>
    let (g, r) := mtrial (s + 1) 8
    (acc.1 + (if g then 1 else 0), acc.2.1 + r, acc.2.2 + 4)) (0, 0, 0)

#eval runMutation 200
#eval synthQueue 8 7
#eval priceTime (synthQueue 8 7) 2500
#eval corrupt (priceTime (synthQueue 8 7) 2500) 0 7
#eval (conformsPT (synthQueue 8 7) (priceTime (synthQueue 8 7) 2500) 2500,
       conformsPT (synthQueue 8 7) (corrupt (priceTime (synthQueue 8 7) 2500) 0 7) 2500)

-- Parity fingerprint: one un-truncated pass over 5 participants prints five equal lots.

#eval (wheelRound 100 [300, 500, 200, 1000, 400] 2000).1
-- Balance check on a synthetic wheel run (allocated, remaining).
#eval (wheelS 100 40 (initS (synthQueue 6 3)) 1700).1

end Rule737
